### ISSUE TITLE
Liquidation of balls that have fallen into buckets.

### ISSUE THREAD

**Issue by AlistairWestmacott** [ThisIsSoNotMe/GaltonBoards#12]
When balls fall into buckets, they currently stack on top of each other meaning you get no useful information from stacked balls. I think this could be fixed by changing the getMesh and getUVs method of both buckets and balls. If a ball is in a bucket then don't render it and if a bucket has balls in it then add another quad with size relating to the number of balls in the bucket.

**Comment by AlistairWestmacott** [comment]
The way this interacts with colouring is going to be complicated.

**Comment by LRudL** [comment]
Balls are now getting liquidated. These issues remain:

- balls are not rendered while falling in the top half of the bucket because that part is solid white and I think the ball is “behind” it
- balls liquidate only when hitting the bottom of the bucket, not the liquid level
- no support for colouring by tag yet

**Comment by LRudL** [comment]
Liquidation, tagging, and rendering/colouring accordingly all work, so this is effectively completed. We can create new issues for any graphics fine-tuning in the future.
