### ISSUE TITLE
Performance issues after a short amount of time from having too many balls in the simulation.

### ISSUE THREAD

**Issue by AlistairWestmacott** [ThisIsSoNotMe/GaltonBoards#13]
After a short amount of time (approx 30s), the frame-rate start to slow. After profiling, it was determined that this is due to the repeated array concatenation in all the getMesh methods. Therefore a possible solution is changing the data structure used to construct the mesh buffer. Something which isn't O(n) on concatenation as that is causing massive performance problems.

**Comment by LRudL** [comment]
I changed the getMesh/getUV/getColourTemplate functions on Balls to return an empty array if the ball is in a ColumnBottom (i.e. at the bottom of a bucket), since in this case the ball is already in the bucket and "rendered" as part of the bucket's liquid. This improves performance significantly – previously the board would start lagging (at maximum ball speed and rate, as set in the UI) after around 10s for me, but now I can run it for much longer with no significant lag.

Since every ball eventually ends in a bucket, and bucket liquid rendering is fast, this should solve the problem (number of balls in transit doesn't increase with time), unless there's an extremely large number of flying non-liquid balls. Therefore I'm closing the issue for now, but feel free to reopen if this isn't yet sufficient.
